### ISSUE TITLE
Problems with using event constructors

### ISSUE THREAD

**Issue by kramerc** [bluerail/twitter-bootstrap-rails-confirm#18]
Ever since commit 59bf1f91e81ad0dcba18a8c287465719f7448c19 was merged in, Capybara feature specs using either the [capybara-webkit](https://github.com/thoughtbot/capybara-webkit) or [Poltergeist](https://github.com/jonleighton/poltergeist) drivers fail when testing confirmation dialogs powered by this gem. Debugging the failures, I found the following error that is tripping the specs:

```
ReferenceError: Can't find variable: MouseEvents
```

Correcting `MouseEvents` to `MouseEvent` presents another issue. While this resolves the above error in Firefox and Chrome, both Safari and the Capybara drivers give the following error:

```
TypeError: '[object MouseEventConstructor]' is not a constructor (evaluating 'new MouseEvent')
```

With Safari 6.0.5, switching `MouseEvent` to `Event` works as intended. With the Capybara drivers, however, they present a similar error as the one above with `Event`, thus leading me to assume they're working with older versions of JavaScriptCore. There is a related issue regarding this on the PhantomJS repo: ariya/phantomjs#11289

I would suggest either reverting the commit for now or changing `MouseEvents` to `Event` and add backwards compatibility while other browsers and WebKit test drivers catch up.

**Comment by rvanlieshout** [comment]
I've never had any complaints about this issue anymore so closing it. Feel free to reopen if it's still relevant
