### ISSUE TITLE
Callbacks on confirm/cancel?

### ISSUE THREAD

**Issue by jackerman09** [bluerail/twitter-bootstrap-rails-confirm#32]
How can I run a JS function when confirm and/or cancel are clicked? For example, I have it set so that a button is disabled when it is clicked so the user cannot click it twice, however, if 'Cancel' is clicked I need to re-enable the button.

Thanks!

**Comment by rvanlieshout** [comment]
The modal would prevent your second click, but if you would really want you could observe the default bootstrap events like modal's shown?
