### ISSUE TITLE
Gem is loaded, but doesnt hook?

### ISSUE THREAD

**Issue by rmccown** [bluerail/twitter-bootstrap-rails-confirm#36]
Howdy
 I've used this Gem in another project and it works great.  I have just added it to another project, and cannot get it to hook correctly.   It is bundled correctly, I have the correct jquery-rails version, and I see it loaded in the page.

https://www.evernote.com/l/APke39gqD7dNcYdSGaCbY-ChhuM67ZcyzQMB/image.png

Yet I still get the same old boring confirm dialogs!  There are no console or rails log errors.  

Could it be a conflict with another gem?  Another JS module?  (I removed all the other modules from my application.js but it still wont hook)  Is it because I'm getting Bootstrap from a CDN instead of loading it locally?  

Help!

**Comment by jodydawkins** [comment]
What was the resolution to this?
